name: "demo"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2024-05-10"
machine_id: 1

mysql:
  host: "mysql"
  port: 3306
  user: "root"
  password: "0125"
  dbname: "demo"
  max_open_conns: 200
  max_idle_conns: 50
